[workspace]
members = [
  "iroh-mainline-content-discovery",
  "iroh-mainline-content-discovery-cli",
  "iroh-mainline-tracker",
  "tls",
]
resolver = "2"

[profile.release]
debug = true

[profile.optimized-release]
inherits = 'release'
debug = false
lto = true
debug-assertions = false
opt-level = 3
panic = 'abort'
incremental = false


[workspace.lints.rust]
missing_debug_implementations = "warn"

[workspace.lints.clippy]
unused-async = "warn"

[workspace.dependencies]
iroh = { version ="0.34", features = ["discovery-pkarr-dht"] }
iroh-base = "0.34"
iroh-blobs = { version = "0.34", features = ["rpc"] }
# explicitly specified until iroh minimal crates issues are solved, see https://github.com/n0-computer/iroh/pull/3255
tokio = { version = "1.44.1" }
