[package]
name = "iroh-handler-pool"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
iroh = "0.35.0"
n0-future = "0.1.3"
tokio = "1.45"
tokio-util = { version = "0.7", features = ["time"] }
tracing = "0.1.41"
