[package]
name = "iroh-connection-pool"
version = "0.1.0"
edition = "2024"

[dependencies]
iroh = "0.91.1"
n0-future = "0.1.3"
snafu = "0.8.6"
tokio = "1.45"
tokio-util = { version = "0.7", features = ["time"] }
tracing = "0.1.41"
